// auth.js
export const SWITCH_POP_UP_VISIBILITY = "SWITCH_POP_UP_VISIBILITY";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SAVE_LOGIN_ERRORS = "SAVE_LOGIN_ERRORS";
export const SAVE_REGISTER_ERRORS = "SAVE_REGISTER_ERRORS";

// profile.js
export const ON_CHANGE_FIRST_NAME = "ON_CHANGE_FIRST_NAME";
export const SAVE_PROFILE_START = "SAVE_PROFILE_START";
export const SUCCESSFULLY_SAVED_PROFILE = "SUCCESSFULLY_SAVED_PROFILE";
export const PROFILE_SAVE_ERROR = "PROFILE_SAVE_ERROR";
