// auth.js
export const SWITCH_POP_UP_VISIBILITY = "SWITCH_POP_UP_VISIBILITY";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SAVE_LOGIN_ERRORS = "SAVE_LOGIN_ERRORS";
export const SAVE_REGISTER_ERRORS = "SAVE_REGISTER_ERRORS";

// profile.js
export const FILL_PROFILE = "FILL_PROFILE";
export const FILL_PROFILE_ERROR = "FILL_PROFILE_ERROR";
export const SAVE_PROFILE_START = "SAVE_PROFILE_START";
export const SUCCESSFULLY_SAVED_PROFILE = "SUCCESSFULLY_SAVED_PROFILE";
export const PROFILE_SAVE_ERROR = "PROFILE_SAVE_ERROR";

// customHeader.js
export const UPDATE_WINDOW_DIMENSIONS = "UPDATE_WINDOW_DIMENSIONS";
